language: php
php:
  - 5.6

services:
  - mysql

before_install:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

before_script:
  - composer self-update
  - mysql -e 'create database symfony;'

script:
  - phing build-ci-travis
