language: php
php:
  - 5.6

before_install:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

before_script:
  - composer self-update

script:
  - phing build-ci
