<?php

namespace Dig\ApiBundle\Repository;

/**
 * AlbumRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
