<?php

namespace Dig\ApiBundle\Repository;

/**
 * ImageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlbumWithImagesSearchQuery($albumId, $offset, $limit)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->leftJoin('i.album', 'a')
            ->where('a.id = :albumId')
            //->setFirstResult($offset)
           // ->setMaxResults($limit)
            ->setParameter('albumId', $albumId);

        return $qb->getQuery()->getResult();
    }
}
